import Head from 'next/head'
import Form from '../components/Users'
import Link from 'next/link'

export default function AddUser(){
    const userForm = {
        name: '',
        username: '',
        email: '',
        country: '',
        currency: '',
        wallet: '',
        password: '',
    }

    return(
        <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
        <div className='send'>
            <Link href="/" legacyBehavior>
            <button className="btn edit">Home Page</button>
            </Link>
        </div>

            <h1 className='title'>Wallet Send Amount</h1>
            <Form formId="add-pet-form" userForm={userForm} />
        </main>
        </>
    );
}