import Head from 'next/head'
import connectDB from '../utils/connectDB'
import User from '../models/UserModel'
import React, { useState } from "react"
import Link from 'next/link'

export default function TransferAmount({ users }){

    const submitForm = (e) => {
        // We don't want the page to refresh
        e.preventDefault()
    
    }
    
    const handleInput = (e) => {
        const fieldName = e.target.name;
        const fieldValue = e.target.value;
    
        setFormData((prevState) => ({
          ...prevState,
          [fieldName]: fieldValue
        }));
      }


    return(
        <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
        <div className='send'>
            <Link href="/" legacyBehavior>
            <button className="btn edit">Home Page</button>
            </Link>
        </div>
            <h1 className='title'>Wallet Transfer Send Amount</h1>

            <form method="POST" action="/api/users" onSubmit={submitForm}>
        
                <div className='form-group-username'>
                    <label htmlFor="username">Username</label>
                    <select name="username" id="username" onChange={handleInput}>
                    {users.map((user) => (
                        <option value={user._id}>{user.username}</option>
                    ))}
                    </select>
                </div>

                <div className='form-group-username'>
                    <label htmlFor="wallet">Amount</label>
                    <input
                    onChange={handleInput}
                    type="number"
                    maxLength="20"
                    name="wallet"
                    required
                    />
                </div>


                <div className='form-group button-box'>
                <button type="submit" className="btn">
                    Send
                </button>
                </div>

            </form>
        </main>
        </>
    );
}


/* Retrieves pet(s) data from mongodb database */
export async function getServerSideProps() {
    await connectDB()
  
    /* find all the data in our database */
    const result = await User.find({})
    //console.log(result)
    const users = result.map((doc) => {
      const user = doc.toObject()
      user._id = user._id.toString()
      return user
    })
  
    return { props: { users: users } }
  }
  