import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function User({ users }){

    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1>This is User List Page</h1>

            {
                users.map(user => {
                    return (
                        <div key={user.id} className={styles.box}>
                            <p>{user.name}</p>
                            <p>{user.username}</p>
                            <p>{user.email}</p>
                            <p>{user.city}</p>
                        </div>
                    )
                })
            }

        </main>

        </>
    );
};


export async function getServerSideProps() {

    const res = await fetch("https://jsonplaceholder.typicode.com/users")
    const data = await res.json()

    return {
        props:{
            users: data,
        }
    }
};